//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?
//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?
//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜,鍒欏皢瑕嗙洊瀵规鏂囦欢鐨勬墜鍔ㄦ洿鏀广€?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fp_Part.Fp_Model
{
    public partial class AuditRec
    {
        public string id { get; set; }
        public string obj_id { get; set; }
        public string obj_name { get; set; }
        public string user_name { get; set; }
        public string created_at { get; set; }
        public string created_time { get; set; }
        public string message { get; set; }
        public string comments { get; set; }
    }
}